#!/bin/bash
# Install RISE for interactive slide shows
pip install RISE

# Enable the RISE extension
jupyter-nbextension enable rise --py --sys-prefix

# Optionally set an environment variable to signify this is a Binder instance
echo "export BINDER_SERVICE_HOST=true" >> $CONDA_DIR/etc/conda/activate.d/env_vars.sh

# Move the runPresentation.js to its appropriate location
mkdir -p $CONDA_DIR/share/jupyter/nbextensions/
mv runPresentation.js $CONDA_DIR/share/jupyter/nbextensions/
